CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(1000) NOT NULL UNIQUE,
  password VARCHAR(225) NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'user',
  refresh_token VARCHAR(225),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); 

CREATE TABLE IF NOT EXISTS positions (
    position_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    position_code VARCHAR(1000) NOT NULL UNIQUE,
    position_name VARCHAR(300) NOT NULL,
    id INT NOT NULL,  <-- This is your FOREIGN KEY
    is_open BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (id) REFERENCES users (id) 
);